name: Scheduled or Manual Trigger

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  call-main:
    permissions:
      contents: write
    uses: ./.github/workflows/fetch-game-data.yml
    secrets: inherit
    with:
      trigger_source: ${{ github.event_name == 'schedule' && 'scheduled' || 'manual' }}